/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CondominiosRouteImport } from './routes/condominios'
import { Route as AtividadeRouteImport } from './routes/atividade'
import { Route as IndexRouteImport } from './routes/index'

const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CondominiosRoute = CondominiosRouteImport.update({
  id: '/condominios',
  path: '/condominios',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadeRoute = AtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividade': typeof AtividadeRoute
  '/condominios': typeof CondominiosRoute
  '/configuracoes': typeof ConfiguracoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividade': typeof AtividadeRoute
  '/condominios': typeof CondominiosRoute
  '/configuracoes': typeof ConfiguracoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atividade': typeof AtividadeRoute
  '/condominios': typeof CondominiosRoute
  '/configuracoes': typeof ConfiguracoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atividade' | '/condominios' | '/configuracoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atividade' | '/condominios' | '/configuracoes'
  id: '__root__' | '/' | '/atividade' | '/condominios' | '/configuracoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadeRoute: typeof AtividadeRoute
  CondominiosRoute: typeof CondominiosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condominios': {
      id: '/condominios'
      path: '/condominios'
      fullPath: '/condominios'
      preLoaderRoute: typeof CondominiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividade': {
      id: '/atividade'
      path: '/atividade'
      fullPath: '/atividade'
      preLoaderRoute: typeof AtividadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadeRoute: AtividadeRoute,
  CondominiosRoute: CondominiosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
